### ISSUE TITLE
E019: HTTP Status 500 when using IP Adresses as Bookmark

### ISSUE THREAD

**Issue by ikeatgit** [nextcloud/bookmarks#1029]
**Describe the bug**
I am getting only partial syncs with some of my folders. It starts to synchronize, but then i get a E019: HTTP Status 500 error in floccus. Nextcloud shows only a part of my Bookmarks.
After a bit of trial and error the problem seems to occur on Bookmarks which are straight up local IP adresses (https://###.###.##.#/
This is reproducable in Nextcloud(pi) itself, it wont accept a manual entered IP adress as bookmark (either that, or im doing something wrong)

**Expected behavior**
Expected IP Adresses to be accepted as Bookmark ;)

**Desktop (please complete the following information):**
 - OS: [Windows and Manjaro]
 - Browser [Firefox]
 - Version [75]

**Server (please complete the following information):**
 - OS: [Debian Buster with Armbian Linux 4.14]
 - PHP version: [7.3.14]
 - Nextcloud version: [Nextcloudpi 1.25.0]
 

Thanks in advance for this great App!

**Comment by j-ed** [comment]
Unfortunately you haven't search the list of issues before you opened a new one, otherwise you would have found out that this point has already been addressed here: https://github.com/nextcloud/bookmarks/issues/775, https://github.com/nextcloud/bookmarks/issues/931, https://github.com/nextcloud/bookmarks/issues/1018

**Comment by marcelklehr** [comment]
Fixed in the latest release.
