### ISSUE TITLE
Upgrade last version

### ISSUE THREAD

**Issue by danelsan** [nextcloud/bookmarks#1062]
**Describe the bug**

require(): Failed opening required '/var/www/html/custom_apps/bookmarks/vendor/composer/../symfony/polyfill-ctype/bootstrap.php' (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/custom_apps/bookmarks/vendor/composer/autoload_real.php#57","userAgent":"--","version":"18.0.4.2"

**To Reproduce**

Upgrade bookmarks

**Expected behavior**
Right upgrade

**Comment by marcelklehr** [comment]
Does this file not exist on your server?

```
/var/www/html/custom_apps/bookmarks/vendor/symfony/polyfill-ctype/bootstrap.php
```

**Comment by Sephtex** [comment]
I have exactly the same issue, found the error in nextcloud.log on my production upgrade.

The vendor dir exists, but no symfony directory. I also didn't found symfony in the composer.json:
```
{
        "require": {
                "doctrine/inflector": "1.4.*",
                "ext-dom": "*",
                "ext-json": "*",
                "ext-libxml": "*",
                "ext-pdo": "*",
                "guzzlehttp/psr7": "^1",
                "marcelklehr/link-preview": "^3",
                "pguardiario/phpuri": "1.0.*",
                "psr/http-client": "^0.2.0",
                "psr/http-factory": "^1.0",
                "psr/http-message": "^1.0",
                "rowbot/url": "^3.0"
        },
        "require-dev": {
                "phpunit/phpunit": "^8.5"
        },
        "config": {
                "optimize-autoloader": true,
                "classmap-authoritative": true
        },
        "scripts": {
                "lint": "find . -name \\*.php -not -path './vendor/*' -print0 | xargs -0 -n1 php -l"
        }
}

```
This happened on my production setup, while the upgrade succeeded on my QA.
The only difference here is that the apps directory was never cleaned up since v13 of nextcloud.
On my QA installation, which has a complete fresh setup of v18 doesn't have the bookmarks in the app directory.

As a last resolution, I cleared the apps directory, and did a fresh installation using a mysql backup, and it succeeded!

So I think that the bookmarks app should have been cleaned up somewhere in the upgrade process?
Or maybe I needed to run `./occ app:update --all` before `./occ upgrade`? (which doesn't make sense IMO)

**Comment by marcelklehr** [comment]
Symfony deps are present in the latest packages of the bookmarks app. As mentioned I suggest to remove the bookmarks app. Update nextcloud, then update the bookmarks app.
