### ISSUE TITLE
Design: Change app logo?

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#1083]
Hey @nextcloud/designers @nextcloud/designlearners @jancborchardt @skjnldsv 

![favicon](https://user-images.githubusercontent.com/986878/85204199-208bba00-b313-11ea-8f70-fb047f2553a6.png)

I was thinking about the current logo of the bookmarks app (the star) and how it's not really a good fit. It clashes with the normal "favorites" icon and is also a bit too generic for my taste. Some of the famous icon libraries offer some good alternatives and also there are some inspirational emojis:

# :book: :bookmark: :bookmark_tabs:

Do you think we should change the logo? And if yes, would be able to suggest a new one?

**Comment by stefan-niedermann** [comment]
The bookmark label in the middle looks good but can also clash with the tags in Nextcloud...

**Comment by jancborchardt** [comment]
Let’s see what others use:

## Firefox: star
![image](https://user-images.githubusercontent.com/925062/85204339-259d3900-b314-11ea-8c30-4c6e8206ee0c.png)

## Chrome: star
![chrome bookmark](https://user-images.githubusercontent.com/925062/85204427-b2e08d80-b314-11ea-8bb2-c646e2dad4d9.png)

## Safari: book
![](https://www.imore.com/sites/imore.com/files/styles/xlarge/public/field/image/2018/08/safari-ios-bookmark-search-screens-1.jpg)

------------

Since Chrome is the most-used browser by far on desktop as well as mobile, and Firefox is also using the same iconography, I’d say the star is a pretty good fit.

**Comment by marcelklehr** [comment]
@jancborchardt Thanks, I agree that it's a very intuitive logo. What's your take on possible confusion between "favorite X" and "bookmarks"?

**Comment by jancborchardt** [comment]
I'd say that's fine, as they _are_ favorites – favorite websites, that is. ;)

Chrome and Firefox would face the same issue anyway, so I'd say in doubt it's better to stick with the convention.

**Comment by dasbiswajit** [comment]
I love the current logo though 👍

**Comment by marcelklehr** [comment]
Alright :) Thank you for your input! :blue_heart:

**Comment by Bugsbane** [comment]
Might I suggest that yes, we keep the star, but just adjust the star to use straighter lines so it's not quite so round, similar to the Chrome star (and I say this as an avid Firefox user). I feel that it would look cleaner and more professional, especially at smaller icon sizes. The current star imo, looks a bit too "kids carnival" style for my tastes, although I do agree with @jancborchardt 's reasons for using a star per se. Happy to do a mockup if desired.
