### ISSUE TITLE
Implement website history based on screeenly

### ISSUE THREAD

**Issue by florianwgnr** [nextcloud/bookmarks#1128]
**Describe the solution you'd like**

At the moment screeenly is implemented to take screenshots of web pages. 

As mentioned in #558 these images are "cached for 4 months in data, encoded as a base64-string in a json file".

My suggestion would be an option to display a list together with a timestamp and the belonging fullscreen-image. So if a web page shuts down, i can still read or see what it was like (like "the internet wayback machine" or wallabag - light).

The advantage is: capturing and storing screenshots is already implemented and my solution is therefore - from a non-programmers view - easier to implement than wallabag or else.

This feature request might be linked to #524 and could be a lighter version of wallabag or of the internet wayback machine.

**Comment by marcelklehr** [comment]
Hey @florianwgner!

Thank you for taking the time to provide feedback! :) I think if we're going for something like archive funcitonality, we should use a text/html format for that rather than screenshots, aka. #438, which is on my todo list. Your suggestions goes a step further in that you suggest to store multiple historic versions of the webpages. I don't see this as too important for now, but can definitely see the value of this. I'm closing this for now, but feel free to add a comment about historic versions to #438 :heart:

**Comment by bonswouar** [comment]
@marcelklehr Now that "text screenshots" are implemented, would you consider adding an "history" feature?

_Just for the context, I've only recently tried this Bookmark plugin as I felt like I didn't need it, and seeing the actual features it's already much more useful than I first thought. **A revision history would make it totally indispensable**!_

**Comment by marcelklehr** [comment]
> seeing the actual features it's already much more useful than I first thought.

Cool! Which features were you not aware of? :)

> A revision history would make it totally indispensable!

I'll need to think about it. Can you create a new issue for this?

**Comment by bonswouar** [comment]
> Cool! Which features were you not aware of? :)

The broken link & text screenshot features! (yes I didn't read the description very attentively haha)
And I got kinda surprised seeing how painless Firefox synchronization was ;)

> Can you create a new issue for this?

Done! #1762 :)
