### ISSUE TITLE
Huge useless padding

### ISSUE THREAD

**Issue by simmstein** [nextcloud/bookmarks#1227]
**Describe the bug**
Huge padding on left and on the right of the list.

**To Reproduce**

Install the version >= 3.4

**Expected behavior**

Use all the space like versions <= 3.4.

![](https://upload.deblan.org/u/2020-10/5f759cb7.png)

**Screenshots**

![](https://upload.deblan.org/u/2020-10/5f759c5f.png)

**Comment by simmstein** [comment]
Workaround using [Custom CSS](https://apps.nextcloud.com/apps/theming_customcss):

```
.bookmarkslist .padding {
  max-width: 100% !important;
}
```

**Comment by marcelklehr** [comment]
This is a feature recommended by the designers to optimize readbility.

**Comment by simmstein** [comment]
This is inconsistent with others lists (files, apps).

**Comment by marcelklehr** [comment]
cc @nextcloud/designers

**Comment by weeman1337** [comment]
> This is a feature recommended by the designers to optimize readbility.

Uff. Great improvement of readability for example not aligning the content to the header (breadcrumbs etc.).

**Comment by jancborchardt** [comment]
Going full width would be very bad for usability here, because the name of the entry and the menu are maximally far away from each other. Having a max-width is very common (see Github, Microsoft Teams, Twitter, etc etc). We also do it in Talk, Text, Mail, and other apps.

> not aligning the content to the header (breadcrumbs etc.).

As per other design recommendations, the breadcrumb should instead be a heading of the current bookmarks folder, much like in Photos.

> This is inconsistent with other lists (files, apps, etc.).

Yes – they can use some improvement work too.

**Comment by marcelklehr** [comment]
thanks for weighing in @jancborchardt :heart:
