### ISSUE TITLE
Missing bookmark screenshots / icons

### ISSUE THREAD

**Issue by bspire** [nextcloud/bookmarks#1252]
**Describe the bug**
No bookmark screenshots / icons are created anymore.

**To Reproduce**
Create a new bookmark.

**Expected behavior**
When creating a new bookmark, a screenshot / icon of the corresponding webpage shall be taken.

**Screenshots**
![nextcloud_bookmarks_no_screenshots](https://user-images.githubusercontent.com/24420694/95688519-2af7f980-0c0b-11eb-9399-a87ec2e2f4da.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Browser: Microsoft Edge
 - Version: 86.0.622.38

**Server (please complete the following information):**
 - OS: Debian 10.6
 - HTTP server: Apache
 - Database: MySQL
 - Nextcloud version: 19.0.4
 - Bookmarks app version: 3.4.1

**Comment by marcelklehr** [comment]
Have you enabled network access in the bookmarks app settings?

**Comment by CharlBest** [comment]
I'm also having this issue. I don't see an option to enable network access in the bottom left settings area.

**Comment by marcelklehr** [comment]
It's in the admin settings

**Comment by CharlBest** [comment]
Thanks for the quick reply. That did the trick and it is working now.
For anyone with the same problem:
![image](https://user-images.githubusercontent.com/6147400/95734537-7d70fe80-0c7b-11eb-962b-1a942b8e23f1.png)

**Comment by coderonline** [comment]
Hi! The setting is not applied for me, even though there is a check mark shown in the upper right corner after activating the option. After revisiting the page it is off again. I started debugging that a bit and used the Firefox Web Developer Tools to identify possible causes, but nothing interesting there. A POST request to `https://[domain]/ocs/v2.php/apps/provisioning_api/api/v1/config/apps/bookmarks/privacy.enableScraping` succeeded.

I have several questions about the App:

* Where does Nextcloud Bookmarks usually store its config values?
* Is it also possible to toggle the privacy option using `nextcloud/config/config.php`?
* In Nextcloud under `Logging` there is no error message. Does Nextcloud Bookmarks possibly use its own error log? Where would a `permission denied` error be logged (because I have intentionally some files not owned by the `www` user in my Nextcloud installation)?

**Comment by marcelklehr** [comment]
With the latest version of the app the settings experience should be improved, hopefully it works now.

**Comment by marcelklehr** [comment]
Any news? @coderonline Did you manage to change the setting and it worked?

**Comment by coderonline** [comment]
@marcelklehr I have already tried the checkbox and it seems to work. Thank you for that. Sorry that I did not respond earlier, but I was planning to perform some further tests and forgot about that during my Easter holidays.
