### ISSUE TITLE
App Store description should not contain system requirements

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/bookmarks#1304]
Hello Marcel,

actually the App Store page looks like

<img width="899" alt="Bildschirmfoto 2020-11-03 um 20 10 40" src="https://user-images.githubusercontent.com/2069590/98030075-c2b6c500-1e10-11eb-9d33-afb6a91524cc.png">

The requirements are for which NC release?
Actually 20? Then php version is not correct.

Why not removing this part?

**Comment by rakekniven** [comment]
Just seen the page has been updated.

Still I am questioning why the app store page is showing requirements?

**Comment by marcelklehr** [comment]
Hi :) 

Apps are allowed to have requirements that differ from the nextcloud requirements. Last time I checked, neither the app store nor the apps section in nextcloud server display those requirements, while the apps section in server does adhere to the app-specified requirements. That's why I added them to the description.

**Comment by rakekniven** [comment]
Ok, understood.

Have a nice sunday evening.
