### ISSUE TITLE
Link to Deck 

### ISSUE THREAD

**Issue by Peachy74** [nextcloud/bookmarks#1492]
it would be wonderful if you could assign link folder to a card in deck.
it is complicated to realize this

**Comment by stefan-niedermann** [comment]
As stated in https://github.com/nextcloud/deck/issues/2941#issuecomment-813103673 i recommend to implement support for Nextcloud projects. This will not only allow an integration with various Deck entities (boards & cards) but also with files, folders and talk rooms.

**Comment by marcelklehr** [comment]
Good idea! Is there any documentation on how to integrate with projects? (@stefan-niedermann)

**Comment by stefan-niedermann** [comment]
@marcelklehr no it's horrible. I reverse engineered most of the stuff by sniffing the Web UI for read-only support in the Deck Android app. @juliushaertl should be able to point you to some documentation (or code form the Deck app) or at least know someone who knows :smile:

**Comment by marcelklehr** [comment]
@stefan-niedermann oof.

**Comment by sunjam** [comment]
[Here is another post referencing Bookmarks & Deck support](https://github.com/nextcloud/deck/issues/2529) in issue 2529.  "Attach bookmarks to cards"

**Comment by juliushaertl** [comment]
Yes, we unfortunately don't have documentation for that until now, but here are some quick pointers on what would be required in order to let your app support projects.

## Register a resource provider

https://github.com/nextcloud/deck/blob/840c143b92167953e8f4aa326b13da162f03f5c3/lib/AppInfo/Application.php#L202
https://github.com/nextcloud/deck/blob/6910ba95fae2da0eed07a0a6aa54d4d35abf56ee/lib/Collaboration/Resources/ResourceProvider.php

## Register your provider in the frontend

```
OCP.Collaboration.registerType('files', {
    // This function is called when the user selects the entry "Link to a file" in the multiselect input
	action: () => {
		return new Promise((resolve, reject) => {
			// show your picker here and resolve it with the unique id for your resource that can be used in the backend then
		})
	},
	typeString: 'file',
    typeIconClass: 'icon-files-dark'
});
```

https://github.com/nextcloud/spreed/blob/ddf06db9028910782c2eefe888d7eeb1eba554c3/src/collections.js#L38


## Load a script on all pages that offer a projects input in order to then show a picker for your resource type (e.g. select a bookmark to link to)

https://github.com/nextcloud/deck/blob/840c143b92167953e8f4aa326b13da162f03f5c3/lib/AppInfo/Application.php#L205-L211

I hope this helps as a starting point, but please just ping in case of questions.

**Comment by marcelklehr** [comment]
@juliushaertl Thanks for the explainer! After going through these steps I get a 404 from `nextcloud.local/ocs/v2.php/collaboration/resources/bookmarks/13060?format=json` upon trying to link a bookmark with something else (fails both with files and talk rooms). Any hints what could be the cause?

**Comment by marcelklehr** [comment]
Done.
