### ISSUE TITLE
Bulk editing

### ISSUE THREAD

**Issue by gerroon** [nextcloud/bookmarks#157]
Hi
It is very tedious to delete bmarks one by one. It would be useful if it was possible to select multiple bmarks and delete them.

**Comment by viki53** [comment]
+1

Selecting several bookmarks in general would be great for bulk actions:
* Deleting
* Applying tags
* Moving to a folder (if this functionality gets developed)
* Exporting a selection

**Comment by koreywithak** [comment]
I'd like to reiterate @viki53 and also ensure items from the referenced #396 are incorporated, namely:
- More advanced filtering
- I like folders, but if using tags there should still be an option for nesting. See what Gmail has done with multilevel tagging (similar to a folder hierarchy).
- More ways to sort bookmarks
- Import/Export to include all tagging or hierarchy information (if tags/organization get lost during import/export that'll kill any use of such an app for me)

**Comment by plantarum** [comment]
I understand this is supposed to be addressed by #424 but I am currently unable to delete more than one bookmark at a time. If I tick the boxes for multiple bookmarks, then select the ellipsis (...) marker and click on delete, only the active bookmark is deleted. Any other bookmarks that I've selected are left undeleted.

Is there something else I need to do to bulk delete, or has something changed since #424?

Thanks,

Tyler
nextcloud 17.0.1
bookmarks 2.3.4
