### ISSUE TITLE
Go to administrator settings for the bookmarks app to allow fetching previews and favicons.

### ISSUE THREAD

**Issue by szvan** [nextcloud/bookmarks#1570]
**Describe the bug**
A pop up appear opening bookmarks app : Network access is disabled by default.Go to administrator settings for the bookmarks app to allow fetching previews and favicons.
In fact, the bookmarks app can't refresh and create favicon...

**So where is the admin settings page mentioned and how to allow internet access for the app ?**

**To Reproduce**
1. Go to bookmarks app icon on Nextcloud
2. On mouse hover, a popup appear : _Network access is disabled by default.Go to administrator settings for the bookmarks app to allow fetching previews and favicons_.
AND
1 : choose a bookmark and click on 3dots menu, choose _Property_
2 : it display : _Content pending- This content is being downloaded for offline use. Please check back later._  

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser: Firefox
 - Version: 89

**Server (please complete the following information):**
Share hosting

**Comment by marcelklehr** [comment]
Hello @szvan 

I have created a screencast for you.

![Peek 2021-06-07 18-17](https://user-images.githubusercontent.com/986878/121054905-16312d00-c7bd-11eb-834b-b6d328d14d35.gif)

**Comment by szvan** [comment]
Thanks a lot ...

**Comment by eoghanmurray** [comment]
This is something I encountered as a new user with the latest software; it's the first time using the nextcloud admin and I appreciate that this is on an app.  I was hunting around for at least 10 minutes in the settings getting increasingly frustrated as to how to enable this.

One problem is that it's not clear that under the `/settings/admin/security` that the 'Administration' includes app administration.  E.g. this section has plenty of items that are general and not related to apps.

Even then when I found the 'Bookmarks' entry, it wasn't clear that this related to the 'Bookmarks App' rather than generic bookmarks that might be available in the stock Nextcloud before I installed a third party app.  

Even after that, the problem was that there is a difference in terminology; in the bookmarks app the problem is described as "Network access is disabled by default"  whereas in the settings section, the checkbox reads "Privacy ... Enable accessing and collecting information ..."
Those terms 'Network access' and 'privacy' don't seem like they could be talking about the same thing.

This can be solved by a 'show don't tell' approach, i.e. give a link to the correct admin section in the original error message (assuming you are an admin).
