### ISSUE TITLE
Drag and drop doesn't work in Chrome

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#1572]
**Describe the bug**
Specifically dropping bookmarks onto folders/tags doesn't work.

**To Reproduce**
1. Create folder
2. Drag bookmark onto folder
3. Drop Bookmark
4. No drop indication, no reaction after drop, nothing happens, no error

**Expected behavior**
The bookmark should be moved.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chromium
 - Version: Version 91.0.4472.77 (Official Build) snap (64-bit)

**Comment by iirekm** [comment]
The same in Chrome 97.0.4692.71 (from deb package) , Kubuntu 20.04
The same is when I try to detach browser tabs: tab detached from a window can't be reattached again, so in general whole drag&drop in Chrome seems broken.

**Comment by deragon** [comment]
Confirming with Ubuntu 20.04 LTS, Chrome 97.0.4692.71 (Official Build) (64-bit) under Gnome.  Since it seams to happen with both KDE and Gnome, the problem seams more to do with Chrome than with the Window Manager.  Drag and drop of bookmarks works well with Firefox 96.0 (64-bit), again suggesting that the problem is not the Window Manager.

It stopped working about a month ago.  Since then, managing bookmarks in Chrome has become a pain.  :(

**Comment by marcelklehr** [comment]
> so in general whole drag&drop in Chrome seems broken

huh. that's a new one :/

**Comment by iirekm** [comment]
Out of curiosity I also checked Edge (the same engine), and the same situation: drag&drop of tabs & bookmarks stopped working. 
Firefox (different engine) has no problem with either tabs and bookmarks.

To me it's hard to tell when the issue began, but I guess it's not longer than month, maybe 2 months, I didn't notice anything wrong previously.

**Comment by deragon** [comment]
Confirming also the tab reattachement is not working anymore.

**Comment by MircoL** [comment]
Confirming this issue as well.

- OS: Linux Mint 20.3 x86_64
- DE: Cinnamon
- Chrome Build: Version 97.0.4692.71 (official build) (64-Bit)

**Comment by alexbramford** [comment]
Confirming this is an issue:

```
Google Chrome | 97.0.4692.71 (Official Build) (64-bit)
-- | --
Revision | adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}
OS | Linux
JavaScript | V8 9.7.106.18
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --enable-crashpad --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=CaptureHandle
Executable Path | /opt/google/chrome/google-chrome
Profile Path | /home/alexb/.config/google-chrome/Default
```

```
screenfetch -n

 alexb@tma7.spaceodyssey.2001.com
 OS: Fedora 
 Kernel: x86_64 Linux 5.15.14-200.fc35.x86_64
 Uptime: 4h 30m
 Packages: 2382
 Shell: bash 5.1.8
 Resolution: No X Server
 DE: KDE 5.89.0 / Plasma 5.23.4
 WM: KWin
 GTK Theme:  [GTK2/3]
 Disk: 1.9T / 2.7T (72%)
 CPU: Intel Core i7-7500U @ 4x 3.5GHz [59.0°C]
 GPU: Mesa Intel(R) HD Graphics 620 (KBL GT2)
 RAM: 7544MiB / 31968MiB
```

```
cat /etc/redhat-release 
Fedora release 35 (Thirty Five)
```

**Comment by marcelklehr** [comment]
Can you try the following drag and drop example, to check whether it's really a Chrome issue?

https://www.w3schools.com/HTML/tryit.asp?filename=tryhtml5_draganddrop

**Comment by RobinVogel** [comment]
I have the same issues and cannot drag and drop the image with Google Chrome browser, although I can in the Firefox Web Browser.

Google Chrome 97.0.4692.71

Selected info from `screenfetch -n`
```
OS: Ubuntu 20.04 focal
 Kernel: x86_64 Linux 5.11.0-46-generic
 Shell: bash 5.0.17
 Resolution: 1920x2160
 WM: i3
 GTK Theme: Yaru-dark [GTK3]
```

**Comment by ArchI3Chris** [comment]
Same here on Arch Linux with I3.

Just ran an upgrade today. I had similar issues before with several former versions of Chromium. But they were there only occasionally and before they always went away with some actions, like opening new windows and tabs and dragging and dropping a bit or restarting.

Not today after the upgrade (note: has been a while). I tried it multiple times, restarted Chromium like 3 times... Still cannot rearrange tabs, bookmarks in the bookmarks manager, drag the URL into the bookmarks bar... Nothing drag and drop working. Same for marcelklehr's example.

Also, same symptoms as described by others before. No indicator for the drop, no drop. Drag theoretically seems to work. At least looks that way.

Chromium version 97.0.4692.71 too. Note: this is a default Dell Latitude Notebook with quite basic setup. So, there is nothing special about this device, like touch or anything. By far not the newest either. Also, before today I had this device working day in and day out for weeks. Meaning, there are no issues with drivers or graphics or anything.

Next to that, also worth mentioning, there have been more issues lately. For quite a while now older versions went quite high in RAM and CPU load and they also crashed beyond repair many times. Crashing in this case means, at some point they stopped rendering and just sat there like ghost windows until I killed and restarted Chromium. That problem has been going on for a while now but hasn't been there before either. Also, this thing just works for a while without problems, then without apparent reason quits working. For a while I thought, it had to do with high load. But no! I watched it happen without high load too. In fact, even without prior action... even with the browser just sitting there.

Speaking of: another one I noticed is, that before when I closed multible tabs (close tabs on the right, close other tabs) the load was reduced appropriately. In the last version I had installed (don't know which one it was) I had to start closing tabs one by one to get Chromium to drop the load. Using close right tabs of close other tabs would not reduce the load. Aside from that I also sometimes noticed, that the load went UP instead of down when I closed tabs.

So, in the past... I'd say... like 2 months or so... there has been a lot of fishy stuff going on with Chromium. I didn't have these issues before. No other that I remember either. But they came up one after the other and have been there for a while now. So far there have always been options to kind of go around the issues. But at this point this is starting to affect my productivity massively. Load is always a problem. But I've been using drag and drop a lot for years. It's one thing to be bothered and to have to play around to get things working. But it's a different thing when basic stuff like drag and drop and load management stop working all together.

Hmm... seems, at least the useless inter-menu for the favorites icon is gone again in the new version. That was just another useless thing to just add clicks instead of being helpful.

**Comment by marcelklehr** [comment]
Alright, since this sounds like a Chrome bug, please file an issue on their issue tracker :pray: I will mark this as upstream.

**Comment by ArchI3Chris** [comment]
Uhmm... right! I came from Google and just saw the headline and missed the repo. No... I don't know about NextCloud at this point. But this is definitely an issue with Chromium and it seems everything derived from it ;)

> Alright, since this sounds like a Chrome bug, please file an issue on their issue tracker pray I will mark this as upstream.

**Comment by marcelklehr** [comment]
> I came from Google and just saw the headline

hello, stranger from Google :wave: :sweat_smile:

> But this is definitely an issue with Chromium and it seems everything derived from it ;) At least as far as I'm concerned.

Great! Thanks for your input anyway :)

**Comment by MircoL** [comment]
> Can you try the following drag and drop example, to check whether it's really a Chrome issue?
> 
> https://www.w3schools.com/HTML/tryit.asp?filename=tryhtml5_draganddrop

Works on Firefox, does not work on Chrome.

**Comment by alexbramford** [comment]
PSA from another stranger from Google:

With this morning's package updates to Chrome (on Fedora 35) these two issues appear to be resolved 

- Drag and drop of bookmarks works as expected
- Tab reattachment works as expected 

```
usr/bin/google-chrome-stable --version
Google Chrome 97.0.4692.99
```

**Comment by marcelklehr** [comment]
Cool. I'm closing this, then :)

Happy dragging and dropping everyone!

**Comment by ArchI3Chris** [comment]
Just to let you know: the issue was gone with the upgrade in January and I had no issues since. Yesterday I ran an upgrade on one of my devices and with version 102.0.5005.61 the issue reappeared. I ran an upgrade on another of my devices today. Same version same problem now. So, the issue is back. No drag and drop for bookmarks in Chrome 102.

**Comment by markusrothenbacher** [comment]
> Just to let you know: the issue was gone with the upgrade in January and I had no issues since. Yesterday I ran an upgrade on one of my devices and with version 102.0.5005.61 the issue reappeared. I ran an upgrade on another of my devices today. Same version same problem now. So, the issue is back. No drag and drop in Chrome 102. Same issue with tab re-ordering too. Not possible to re-order tabs in the same window. It always separates a tab in a new window, if I try to drag it. Seems pretty much the same as before.
> 
> Issue reported: https://bugs.chromium.org/p/chromium/issues/detail?id=1330158 Please confirm, if you run into related issues! Thanks.

Running Ubutnu 22.04 with i3 and Chrome 102.0.5005.61 
Drag&Drop Issue reappeared for me too.
