### ISSUE TITLE
Disable offline use/archiving

### ISSUE THREAD

**Issue by Exagone313** [nextcloud/bookmarks#1605]
**Is your feature request related to a problem? Please describe.**
Since I updated the app, it seems to download web pages for archiving or "offline use". While this feature may be useful for some, I wish to disable it, as it uses unnecessary disk space for my use of the app.

**Describe the solution you'd like**
I'd like to be able to disable archiving and delete data that has been downloaded so far. This doesn't include favicons.

**Describe alternatives you've considered**
Running a cronjob to remove the data manually, or forking the app (if I get the time).

**Additional context**
This feature seems to have been added at the same time "network access" was needed to be enabled in administration settings. I'm not completely sure, maybe it was part of the app a long time before and I didn't notice it.

**Comment by marcelklehr** [comment]
Yes, this feature is new in v4.3.0. I don't intend to add a setting to disable it. The text of a web page costs quite little disk space, which IMHO doesn't outweigh the benefits of full-text search and archival. I'm sorry, but I have to choose carefully which preferences I introduce.

**Comment by jacobgkau** [comment]
This "feature" is quite disruptive. Every time I add a bookmark, I now get stuck on a "saving content for offline use..." screen, and I can't get back to the bookmarks list without reloading.

**Comment by marcelklehr** [comment]
@jacobgkau There is a close button in the top right corner of that screen, I agree, though, that it's sometimes not visible depending on the colors in the page screenshot.

**Comment by jacobgkau** [comment]
I actually discovered that my server was running out of memory when attempting to save content for offline use. It's a $5/month DigitalOcean droplet with 1GB of RAM.

> The text of a web page costs quite little disk space, which IMHO doesn't outweigh the benefits of full-text search and archival.

I'm really questioning this logic. Is this a bookmarks app or an archival app? My bookmarks library currently has over 5,400 bookmarks. Others may have more. You cannot claim that the feature as a whole "costs quite little disk space" when the number of bookmarks and the potential size of each page being bookmarked are limitless.

(I already knew this app wasn't tested with large numbers of bookmarks, as I had to start breaking down my folders into 100-bookmark sets when I switched to this app, since going above 200 resulted in extremely long folder loading times due to the way favicons are handled.)

Beyond full text search, the latest version of this app created a "Bookmarks" folder in my Nextcloud Files that includes a number of images, json files, and other artifacts-- it's all very messy. And some of my bookmarks are of YouTube videos and similar media, which obviously _aren't_ being fetched, so it's not even an effective archival solution anyway.

**Comment by marcelklehr** [comment]
@jacobgkau Thank you for your feedback. Please watch your tone and [read the Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

**Comment by jacobgkau** [comment]
> @jacobgkau Thank you for your feedback. Please watch your tone and [read the Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

Please explain where and how my message violated the Code of Conduct, @marcelklehr.

**Comment by marcelklehr** [comment]
> Please explain where and how my message violated the Code of Conduct, @marcelklehr.

I do not object to anything you say, nor can I change your opinion, but, from my point of view, your comments on this issue so far were neither respectful nor considerate or collaborative. The Code of Conduct as I understand it is not something that can be formally violated, but rather serves as a guideline for building a fruitful environment and community spirit. I've added some quotes from the Code of Conduct, I believe to be relevant.

> We expect members of our community to be respectful when dealing with other contributors, users and communities.

> As a user, remember that contributors work hard on their part of Nextcloud and take great pride in it. If you are frustrated your problems are more likely to be resolved if you can give accurate and well-mannered information to all concerned.

> As a user, your feedback is important, as is its form. Poorly thought out comments can cause pain and the demotivation of other community members, but considerate discussion of problems can bring positive results. An encouraging word works wonders.

Concretely:

- If you have problems with large numbers of bookmarks, feel free to open an issue directly.
- If you get errors with the full-text archiving feature, feel free to open up a new issue.
- If you do not understand the point of a feature, feel free to open a new issue asking that question.
- If you wish to criticize the development of this app, feel free to open a new issue with constructive feedback.

I understand that things can be frustrating, but please remember the human on the receiving end. :hearts:

**Comment by jacobgkau** [comment]
For the record, it looks like @marcelklehr changed his mind about this, as a setting to disable it was finally added in v14:

- https://github.com/nextcloud/bookmarks/commit/6fe0d9ef671e5f72b9d3a5eca7045d4c5a7bcbd3 
- https://github.com/nextcloud/bookmarks/releases/tag/v14.0.0
