### ISSUE TITLE
Automatically generate an archived / snapshot version of the URL.

### ISSUE THREAD

**Issue by jhoos70** [nextcloud/bookmarks#1627]
It would be nice to be able to easily create a snapshot for a bookmark on a site like archive.org for the URl and then have the choice to fetch the original bookmark URL or the archived snapshot version. 

By this the users can ensure the long term availability of the bookmarked information.

**Comment by marcelklehr** [comment]
Bookmark URLs are automatically archived in a fulltext format using readability.php for HTML pages and downloads for files. This is arguably not a full-featured copy, but should be good enough to prevent loss of information. An Archive could theoretically be generated using nextcloud flow see #1466

**Comment by jhoos70** [comment]
Well, that would be something different, as the copy is not public available and is not proven to be not manipulated as it would be on archive.org. But of cause one can do that by hand. Just thought that would be a nice feature.

**Comment by TtuxX** [comment]
I have been a long-term user of this app, ever since it existed in ownCloud.

Over the years I have been regularly pretty sad to see that more and more of my bookmarked URLs and websites died and were broken.
Most of them were not backed-up on Archive.org and I will never be able to view them again. 
I currently have to check broken links and fix them, until the website finally dies.

It would really be awesome to have an activate/deactivate button that would trigger an archive.org download and add a backup archive.org link to the bookmark entry.

Bookmarks would then "truely" become future-proof.
