### ISSUE TITLE
MySQL query runs indefinitely (maxing out all CPU cores)

### ISSUE THREAD

**Issue by Xtropy74** [nextcloud/bookmarks#1727]
### Describe the bug
After Floccus syncs with Bookmarks in NextCloud there is a query that runs and never stops, maxing out all CPU cores

### To Reproduce
1. Sync Floccus to NextCloud
2. On the Server, run: sudo mysqladmin -p processlist
3. See the following nextcloud database process details: 

```
SELECT `b`.`id`, `b`.`url`, `b`.`title`, `b`.`description`, `b`.`lastmodified`, `b`.`added`, `b`.`cl
```

### Expected behavior
The query ends (ended process after 48 hours stuck in this state)

### Desktop
(please complete the following information)
 - OS: Windows 10
 - Browser Chrome and Brave
 - Browser Version 1.33
 - Floccus version: 4.8.7
 - Floccus sync method: nextcloud

### Server
 - OS: Ubuntu 20.04
 - Nextcloud version: 22.2.3
 - Bookmarks app version: 10.0.3

### Additional context

If I disable the "Bookmarks" app in NextCloud, the issue is resolved (but obviously can't use Floccus sync).

**Comment by Xtropy74** [comment]
Issue has resolved itself. Maybe related to a package update on Ubuntu as Nextcloud, Bookmarks and Floccus were not updated.

**Comment by Xtropy74** [comment]
I was wrong same issue came back after a few hours/

**Comment by marcelklehr** [comment]
There are a few other people who experience similar issues: Maybe reading through their comments can help: https://github.com/floccusaddon/floccus/issues/792

**Comment by Xtropy74** [comment]
I am not a database guy, hard for me to follow what people are trying to do here. Looks like you released a fix for this but not working in my case. The state is frozen on "Executing" as well in the processlist. This happens whether or not Floccus is running. Should I just delete all my bookmarks in NextCloud and re-sync them?

**Comment by esbeeb** [comment]
I've had CPU's stuck maxxing out, WRT Bookmarks, and I wasn't even using Floccus.  I had just called up a bookmark from the NC web UI.  I'm using Nextcloud server 22.2.3, Bookmarks app 10.0.3.  MySQL database.  Running from a snap.

This has happened to me now like 3 times.  I end up needing to painstakingly rebooot the server.  But the problem comes again in a few days of weeks.

Hard to reproduce, but it seems possibly the case that aggressively searching for a bookmark, then clicking hinted search results can cause it.  Perhaps there is a race condition in those hinted search results, meaning search results displaying below the search query box, before you've even hit enter yet, but have typed some search text.

**Comment by marcelklehr** [comment]
It could be that the database contains corrupt bookmarks folder remnants. Can you try:

1. Making db backup
2. Running occ maintenance:repair

**Comment by iamhives** [comment]
[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#exec-time-44-14789s-202ms-221s-65s-159s-52s-57s-1)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#lock-time-5-12s-179us-2s-53ms-356ms-227ms-657us-2)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#rows-sent-0-226-1-1-1-1-0-1-3)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#rows-examine-37-7093m-1182k-64505k-32137k-50978k-17500k-39943k-4)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#rows-affected-0-0-0-0-0-0-0-0-5)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#bytes-sent-0-45792k-195k-238k-203k-206k-5930-196k-6)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#query-size-0-29367k-125k-167k-130k-133k-4702-126k-7)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#string-8)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#databases-xyz-9)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#hosts-localhost-10)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#last-errno-1260-11)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#users-xyz-12)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#query_time-distribution-13)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#h-1us-14)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#h-10us-15)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#h-100us-16)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#h-1ms-17)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#h-10ms-18)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#h-100ms-19)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#h-1s-20)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#h-10s-21)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#tables-22)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#show-table-status-from-xyz-like-oc_bookmarksg-23)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#show-create-table-xyzoc_bookmarksg-24)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#show-table-status-from-xyz-like-oc_bookmarks_treeg-25)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#show-create-table-xyz-oc_bookmarks_treeg-26)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#show-table-status-from-xyz-like-oc_bookmarks_tagsg-27)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#show-create-table-xyzoc_bookmarks_tagsg-28)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#show-table-status-from-xyz-like-oc_bookmarks_shared_foldersg-29)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#show-create-table-xyzoc_bookmarks_shared_foldersg-30)[](https://help.nextcloud.com/t/massive-performance-problems-cron-running-forever/133351/4#explain-50100-partitions-31)I just received the following from my hosting provider regarding my cron jobs running forever and Mysql usage going thru the roof: XYZ is my sanitized db name. For now I have disabled the bookmarks app to see if that helps. I have also deleted by bookmarks The browser bookmarks extension Floccus seemed to have problems with lots of bookmarks with lots of subfolders and kept creating duplicates/missing bookmarks and generally corrupting everything and hanfing so may be a combination of these things?

Our server monitoring systems indicate excessive MySQL server load persistently maintained by your hosting account for XYZ.

Most of the MySQL load is caused by the following query:

Exec time 44 14789s 202ms 221s 65s 159s 52s 57s
Lock time 5 12s 179us 2s 53ms 356ms 227ms 657us
Rows sent 0 226 1 1 1 1 0 1
Rows examine 37 70.93M 11.82k 645.05k 321.37k 509.78k 175.00k 399.43k
Rows affected 0 0 0 0 0 0 0 0
Bytes sent 0 457.92k 1.95k 2.38k 2.03k 2.06k 59.30 1.96k
Query size 0 293.67k 1.25k 1.67k 1.30k 1.33k 47.02 1.26k
String:
Databases XYZ
Hosts localhost
Last errno 1260
Users XYZ
Query_time distribution
1us
10us
100us
1ms
10ms
100ms
1s
10s+
Tables
SHOW TABLE STATUS FROM XYZ LIKE ‘oc_bookmarks’\G
SHOW CREATE TABLE XYZ.oc_bookmarks\G
SHOW TABLE STATUS FROM XYZ LIKE ‘oc_bookmarks_tree’\G
SHOW CREATE TABLE ‘XYZ’ .oc_bookmarks_tree`\G
SHOW TABLE STATUS FROM XYZ LIKE ‘oc_bookmarks_tags’\G
SHOW CREATE TABLE XYZ.oc_bookmarks_tags\G
SHOW TABLE STATUS FROM XYZ LIKE ‘oc_bookmarks_shared_folders’\G
SHOW CREATE TABLE XYZ.oc_bookmarks_shared_folders\G
EXPLAIN /!50100 PARTITIONS/
SELECT b.id, b.url, b.title, b.description, b.lastmodified, b.added, b.clickcount, b.last_preview, b.available, b.archived_file, b.user_id, b.text_content, b.html_content, GROUP_CONCAT(tree.parent_folder) AS folders, GROUP_CONCAT(t.tag) AS tags FROM oc_bookmarks b LEFT JOIN oc_bookmarks_tree tree ON b.id =tree.id AND tree.type = ‘bookmark’ LEFT JOIN oc_bookmarks_tags t ON t.bookmark_id = b.id LEFT JOIN oc_bookmarks_tree tr ON tr.id = b.id AND tr.type = ‘bookmark’ LEFT JOIN oc_bookmarks_shared_folders sf ON tr.parent_folder = sf.folder_id LEFT JOIN oc_bookmarks_tree tr2 ON tr2.id = tr.parent_folder AND tr2.type = ‘folder’ LEFT JOIN oc_bookmarks_shared_folders sf2 ON tr2.parent_folder = sf.folder_id WHERE (((b.user_id = ‘me’) OR (sf.user_id = ‘me’) OR (sf2.user_id = ‘me’)) AND (b.user_id IN (‘me’))) AND (b.url = ‘https:deleted url’) GROUP BY b.id, b.url, b.title, b.description, b.lastmodified, b.added, b.clickcount, b.last_preview, b.available, b.archived_file, b.user_id, b.text_content, b.html_content, b.id ORDER BY b.lastmodified DESC, b.id ASC LIMIT 10\G

It appears that the Bookmarks App is making these queries. A possible solution would be to delete all bookmarks.

I'm not a programmer so can't help much but wanted to provide this in case its of any help whatsoever.

Is running occ maintenance:repair necessary because I just upgraded everything to the latest and was under the impression that this repair command was done as part of Nextcloud upgrades?

**Comment by esbeeb** [comment]
I did the occ maintenance:repair, but no notable errors were turned up, related to bookmarks, nor of any kind for that matter (no messages of the nature "such and such problem was detected and solved").  

I'll see if it is better now...

This CPU maxxing out problem was also triggered recently again for me, when doing some light editing in Nextcloud Notes, as well (through web interface).  I wasn't even actively using Nextcloud Bookmarks, and I am the only Nextcloud user on my server.  (Not stable enough to recommend in a multi-user setting, IMHO!)

**Comment by Xtropy74** [comment]
I did the occ maintenance:repair, and while no errors appears, I no longer have the CPU spike so this fixed the issue for me.

Thanks for the suggestion

**Comment by esbeeb** [comment]
After my occ maintenance:repair, the spike came back.  So I exported and then removed all my bookmarks.  Did the CPU spike return again, a few days later?  Yes!  **Even starting with a clean slate of no bookmarks.**

So now I've removed the Bookmarks app altogether.  Let's see if the spike comes back.

**Comment by esbeeb** [comment]
Even after uninstalling the bookmarks app the CPU maxxing problem came back again.  I'm not keen on doing a bunch of sophisticated database administration at this point.

I can say this though: it seems to be a disk I/O thrashing problem, more than a CPU problem.  It's like MySQL is making disk demands so vigorous, that it's impossible to keep up.  I observed the problem this time around both using htop, and iotop.  iotop showed a lot of read churning, like tens of MB/sec, when there was zero demand for all this churn, from any user.

I'm having a crisis of faith in Nextcloud altogether (having been a stalwart supporter since Nextcloud 13).  The thing about cloud services, which the Nextcloud culture seems not to understand, is that they need to be reliable, reliable, and reliable.  All the bells and whistles in the world are completely uninteresting, and I truly wish they didn't exist, so as to bring focus onto the core functionality of reliability and speed.  **Without basic reliability, as a diamond-clad axiom, it's over.**  I need these business-critical functionalities to just work.

**Comment by marcelklehr** [comment]
> Even after uninstalling the bookmarks app the CPU maxxing problem came back again.

Mh, that's weird.

> I'm not keen on doing a bunch of sophisticated database administration at this point.
> ...
> Without basic reliability, as a diamond-clad axiom, it's over. 

Let's keep software politics out of this for now. I'd also have a lot to say on this topic, but that's not the point of this thread. :v:

**Comment by marcelklehr** [comment]
@Xtropy74 have the performance issues resurfaced for you as well meanwhile?

**Comment by esbeeb** [comment]
My nextcloud is in a snap, so I can't figure out execute mysql SQL queries on the command line.  There is a nextcloud.mysql command (from the snap), but what user and what password would I use?  It's not the Nextcloud web admin user and password.  Nor "root", and the Nextcloud web admin password.  Nor is it the root user and root password (for the linux system underneath).

**Comment by marcelklehr** [comment]
> My nextcloud is in a snap, so I can't figure out execute mysql SQL queries on the command line

I'm sorry, I can't help with snap :/

**Comment by esbeeb** [comment]
It is conceivable that my problem lies in some other component of Nextcloud, not Bookmarks.  It's just _my best guess_ that Bookmarks is to blame, since the problematic behaviour matches (with the exception that my problem continued, even after uninstalling the Bookmarks App from the web admin iface).

**Comment by esbeeb** [comment]
> #1661

Here is how my situation is like that other bug:
I had about 1800 bookmarks (before removing them as above).  Plenty of tags.  But did I ever sort the bookmarks into bookmark folders?  Never.

Are there any tags that might make trouble?  Like a tag starting with a dollar sign?

**Comment by esbeeb** [comment]
To try to eliminate any variables at play here, I went through all my Nextcloud apps (which come enabled by default), disabling anything and everything I didn't need, paring it back to that which I knew I actually used.  There were like 12 such things.  One nice side effect: now my contacts load in like 1/2 the time!

**Comment by esbeeb** [comment]
I figured out how to do the SQL query which was asked:

`root@myhost:/# nextcloud.mysql-client nextcloud 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 183
Server version: 8.0.28 Source distribution

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> drop table oc_bookmarks; drop table oc_bookmarks_tags; drop table oc_bookmarks_folders; drop table oc_bookmarks_folders_public; drop table oc_bookmarks_root_folders; drop table oc_bookmarks_shared_to_shares; drop table oc_bookmarks_shares; drop table oc_bookmarks_tree; drop table oc_bookmarks_shared_folders; delete from oc_migrations where app = 'bookmarks';
Query OK, 0 rows affected (0.10 sec)

Query OK, 0 rows affected (0.01 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.01 sec)

Query OK, 0 rows affected (0.01 sec)

Query OK, 0 rows affected (0.01 sec)

Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.01 sec)

Query OK, 0 rows affected (0.04 sec)

Query OK, 15 rows affected (0.00 sec)

mysql> exit`

**Comment by esbeeb** [comment]
The same problem occurred again!  I can't really blame Bookmarks, now that I did that super purge.  Maybe the problem is fundamental to Nextcloud being in a snap somehow?  Like there's something wrong in how the snap was crafted.

**Comment by marcelklehr** [comment]
>  I can't really blame Bookmarks

In that case, I can only refer you to help.nextcloud.com for help with the snap. (Personally, I'm quite skeptical of snaps for hosting web services, I'm more of a docker person.)
