### ISSUE TITLE
URLs with special characters

### ISSUE THREAD

**Issue by Dejieres** [nextcloud/bookmarks#401]
Hello,

Seems to be a little problem with URLs containing special characters when editing a bookmark.

Example :
I added a bookmark for this page : **https://fr.wikipedia.org/wiki/Correspondance_entre_logiciels_libres_et_logiciels_propriétaires** which contains the letter 'é'.
This works fine.

But, if I edit this bookmark, the 'é' is converted and the URL reads now : **https://fr.wikipedia.org/wiki/Correspondance_entre_logiciels_libres_et_logiciels_propri%C3%A9taires**
This occurs as soon as I click on the Edit button.

Clicking on the modified bookmark generates this URL : **https://fr.wikipedia.org/wiki/Correspondance_entre_logiciels_libres_et_logiciels_propri%25C3%25A9taires**
**25** is added after the % sign each time the bookmark is edited...

Did I miss something ?

I use version 0.10.1 on Nextcloud 12.0.2.

Thanks a lot !

**Comment by 4oo4** [comment]
@Dejieres I think what's happening is that it's URL encoding those characters twice. So the second link still works, since 'é' is encoded as %C3%A9, but when you go to edit it it's encoding the % as %25, which breaks the link. Nothing that you would be doing wrong, just looks like a bug that needs fixing. For me, the link breaks just trying to bookmark it, which I'm guessing is because I have NC set to English instead of French.

Pour le moment, l'appli semble de ne pas aimer le français :wink:

**Comment by Dejieres** [comment]
OK :) Thanks for your response.
It's not a critical bug, it's just annoying for languages that use these diacritic signs.

Have a nice day

**Comment by blizzz** [comment]
thanks for reporting :)

**Comment by Exagone313** [comment]
Yeah I just got this problem with spaces (`%20`) in URI. The problem with URI is more complex than it seems, when you have to support both malformed (with non-encoded characters like above) and correct ones.

**Comment by marcelklehr** [comment]
@Exagone313 Escaping shouldn't be used as a way to permanently sanitize values anyway, so that's not a problem and incidentally also not what is happening at the moment. Someone probably just forgot to use the right escape mechanism ;)
