### ISSUE TITLE
Feature Request: Clicking top left corner of thumbnail will “Select” bookmark

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#483]
Hi, I see clicking the top left corner of a bookmark thumbnail doesn’t do anything.  Perhaps clicking the top corner could _Select_ the bookmark.
![ae076a6d-9934-47e5-aae8-ce116e53b331](https://user-images.githubusercontent.com/1787238/39378646-dec7c0c0-4a0d-11e8-8f6b-808d77a8dcb0.jpeg)

**Comment by marcelklehr** [comment]
In an earlier version of the new UI the select box was always visible in the top left corner, but it looked a little too crowded. As a tradeoff, once you have selected one bookmark via the three-dot menu you're automatically in selection mode, allowing you to select additional bookmarks with one click. I'm happy to discuss alternatives, though :)

**Comment by jancborchardt** [comment]
Since selection is a comparatively rare case as opposed to opening, we chose to simply put it in the 3-dot-menu.

The problem is that a clickable area should be at least 44*44px, so that checkmark would need to be that size, even if invisible. And then it would lead to confusion when wanting to open the bookmark, but selection is entered instead.
