### ISSUE TITLE
Improve loading of bookmarks on scroll

### ISSUE THREAD

**Issue by exekutive** [nextcloud/bookmarks#495]
I can't stand the endless scrolling concept (where it only shows you a page of bookmarks, and doesn't load the rest until you scroll to the bottom of the window). I want to see _all_ of my bookmarks. Please, include an option to disable this. I can see how this would make sense on mobile, but there's no reason why they can't all be loaded on desktop.

**Comment by marcelklehr** [comment]
I agree that it can be frustrating to have to wait for the next batch of bookmarks to load, especially when the server isn't the fastest like in my case. I do think we need pagination, though, as there are people who have more than 10,000 bookmarks. We could make the batch size configurable, though. In the latest master version, I've already [increased the batch size to 30 instead of 10 (iirc)](https://github.com/nextcloud/bookmarks/blob/master/js/models/Bookmarks.js#L5).

**Comment by blizzz** [comment]
Totally agree with @marcelklehr. Perhaps we can improve the paging behaviour to trigger loading earlier, e.g. when you have scrolled just half of the height, or have a the next page already loaded, simply show it when the bottom is reached for instant presentation and a smooth feeling and have the next batch being loaded in the background already. This still might not work smooth enough when you scroll down fast. Perhaps it is just good enough.

**Comment by exekutive** [comment]
No. What blizzz describes is precisely what I DON'T want. 
I would prefer to wait until the page fully loads, at least 100 bookmarks, and then see them all at once.
I don't want to have to "trigger" anything. Maybe it could be sped up with some kind of cached index.

**Comment by exekutive** [comment]
Why are you asking as if my request is unusual?  It's like going to a hardware store and asking to see the hammer section and instead, the clerk insists on bringing them out to you one at a time. When I browse my files in Mac or on Windows, it doesn't wait until I scroll to show them to me. To me, THIS triggering feels weird. What if I want to jump to the end of the list? What if I feel like skimming through them?

There was nothing wrong with the way scrolling behaviour always worked. Why do you need to "improve" it? Isn't it more work to program that anyways?

 Do whatever you like, I'm just saying give me the option to use the way I'm used to.

**Comment by marcelklehr** [comment]
> Why are you asking as if my request is unusual? It's like going to a hardware store and asking to see the hammer section and instead, the clerk insists on bringing them out to you one at a time.

I'm sorry if I have upset you. Let me compare the situation to a whole hardware store to show why I think seeing everything at once may not be the best option. If you have a whole hardware store, there's gonna be lots of different things in there. When you go there, you likely don't want to see all of that, but you're looking for something specific.(*) When you need a hammer, you could go through every shelf to see where the specific hammer is you're looking for amidst all the other unordered stuff, something I would compare to "wanting to see all bookmarks at once". If it's a small hardware store that might work. But we need to scale to 10.000 bookmarks. If it's a good hardware store, it won't show you 10.000 items at random. It'll be organized with labels, categories that allow you to trim down the stuff you need to look at to get what you want. That's why in the upcoming version of bookmarks there is search, and there are again tags to organize and filter your bookmarks.
Incidentally, in my opinion this organizational structure is different from a folder-based file system in that you get *everything* by default and have to apply filters. Loading everything at once thus doesn't make much sense, as even in a folder-based file system you don't see everything from every sub directory, but initially you only see the files in the root directory. So, i think it's not that easy to compare the app to a file browser.
I'm not particular about the number of items per shelf in the hardware store / bookmarks per batch being fetched in the app. We should find a sweet spot there between what is acceptable in terms of loading time and what is still useful in terms of content.

**Comment by marcelklehr** [comment]
tbh, even 30 might be a very conservative number as the data being sent per bookmark is not that large.

**Comment by exekutive** [comment]
I think my main point is getting a bit lost, so let me go back and clarify. What makes me frustrated, is the scroll trigger. I really hate it. If you must paginate, then put nice big page numbers right at the top (or even a static bar) where I can easily see and access them. Not scroll around like an idiot. And make the number of items per page configurable. It is very common on retail shopping websites, or eBay search results or whatever. They all let me choose. My brain can easily handle 100 items. Maybe the next guy cannot.

Now let me draw your attention to Firefox bookmarks. Firstly, there is a sidebar with a complete overview of everything on the left side. I realize that right now tags don't work, and I hope Mozilla fixes that soon. For now we have to use folders, and the way they are displayed in Nextcloud is less than ideal. But the overview is important. But if I perform a bookmark search, it shows me EVERYTHING that matches. Then, I can use the column headers to sort how I like, add more search terms, quickly skim from top to bottom, or whatever. But I get an instant idea of what I'm up against. Not 10 items, and who knows how many more hiding from view. I know how to use a scroll bar, and I don't need someone to hold my hand.

I really hate when useful software is ruined by gimicky UI trends that just add more steps and slow down my productivity. (like the latest disappearing scrollbars in MacOS). Programs should serve us, not the other way around. Give people control.

**Comment by sunjam** [comment]
@exekutive Hi, let's stay friendly.

Your issue might be resolved by [Floccus](https://github.com/marcelklehr/floccus/).  A really nice feature of the Floccus extension is that you can sync from the Firefox, Chrome, Opera, or Vivaldi browser root bookmarks directory and then interact with it as you would expect within the browser.

Further, there is now a  [Full Text Search app](https://github.com/nextcloud/fulltextsearch) + extension that [supports Bookmarks search](https://github.com/nextcloud/bookmarks_fulltextsearch) within Nextcloud webui.  These might help your experience.

**Comment by exekutive** [comment]
@sunjam. Don't be so sensitive.

Yes Floccus is fine when I'm on my own machine (I won't even go into the problems Firefox has with bookmarks), but I think that the Nextcloud Bookmarks app needs to stand on its own.

Searching is useful of course, but it does not address my point. It should not take me 5 minutes to scroll through a list.

**Comment by marcelklehr** [comment]
It's always helpful to stay friendly and calm. :)

@exekutive I think you have valid concerns. Apps shouldn't get in the way, they should empower their users. User experience is thus very important, but also a field with many opinions. I've been working on a better and hopefully less frustrating user experience for the bookmarks app for over half a year now. I encourage you to try out [the release candidate available on the app store](https://apps.nextcloud.com/apps/bookmarks) and give constructive feedback by opening issues if you have ideas on what could be improved.

We will definitely think about how the pagination could be improved. I personally don't like pagination using page links, because I often end up having to continuously scroll down and click the 'next' button, when I'm looking for something, which is much less work when the next page just loads automatically, when I'm at the bottom. I think having a config option for how many bookmarks to fetch in one go would probably go a long way by allowing the user to make the trade off between being interrupted more often and having to wait longer. Perhaps an indicator of how many bookmarks are in the result would be beneficial as well. What do you think?

**Comment by exekutive** [comment]
I am completely calm. Don't confuse honesty and unfriendliness ;)

I will try the RC and let you know what I think. How do I install it?

> I personally don't like ... having to continuously scroll down and click the 'next' button
I completely agree. That's why I suggested putting page links at the TOP (in addition to bottom). If I know that something I'm looking for is near the middle, I can jump straight, to page 5 out of 10 for example, without having to scroll. Or lets say I know it starts with the letter 'G' . You get the idea. 

> I think having a config option for how many bookmarks to fetch in one go
Agree

> an indicator of how many bookmarks are in the result
Good idea.

**Comment by exekutive** [comment]
I don't have custom_apps so I extracted it into apps. Now if I try to access my Nextcloud I get a blue screen with "App update required. These apps will be updated:    Bookmarks (bookmarks)"

**Comment by marcelklehr** [comment]
@exekutive that should be fine. You should be able to click on update or something like that and afterwards you'll be redirected to nextcloud home.

**Comment by exekutive** [comment]
ok I see big colourful squares now, and no obvious way to change the view ...

**Comment by marcelklehr** [comment]
@exekutive Yup, then everyting is working. The colorful squares should display previews, but those are only populated when you add a bookmark. You could export your bookmarks and import them again to have the previews appear.

**Comment by jancborchardt** [comment]
@exekutive at Nextcloud, we have some [Design guidelines](https://nextcloud.com/design/). One of that is:

> Software should get out of the way. Do things automatically instead of offering configuration options. When people ask for a setting, find out what the root of the problem is and fix that instead. Also read [»Choosing our Preferences«](https://nextcloud.com/design/).

That is for example why we won’t include a _setting_ for something irrelevant such as the batch size. If you really want to edit that, @marcelklehr showed you where you can do that yourself: https://github.com/nextcloud/bookmarks/blob/master/js/models/Bookmarks.js#L5

We also won’t add pagination, because pagination is meaningless in variable lists. You can never be sure if a bookmark was on page 4 or 5 for example, and that might change over time as you add and remove bookmarks.

------------------

What we can do though is fix the default flow, so that’s why it’s helpful when people tell us their actual _issues_ instead of requests. Then we come up with solutions:
1. Initially load 30 (like now), to keep the first load snappy
2. Load 30 more as soon as that’s done
3. Then load 30 more, so that we’re at 90. (This we could do until a certain point)
4. Trigger the loading of more earlier when scrolling as @blizzz said – people shouldn’t notice that their scrolling loads more stuff, it should already be there when they scroll

Remember that these are first steps, we can always improve on them.

**Comment by exekutive** [comment]
I decided to look for a different bookmark solution.

**Comment by marcelklehr** [comment]
I see. Thanks for your input in any case. I'll close this as fixed for now.
