### ISSUE TITLE
Feature: View mode

### ISSUE THREAD

**Issue by exekutive** [nextcloud/bookmarks#506]
I prefer the old list view over the new icon view. I would like to see a menu option for choosing view mode, so people can choose what suits them better.

**Comment by jancborchardt** [comment]
The issue is that both views will need to be maintained to ensure they work properly. So suddenly that’s double the load, and since it’s only @marcelklehr working on it, for his own sanity I would advise strongly against taking on that work just for legacy support.

Also note that the new view is not only supposed to be "icon view", but also get previews at some point, similar to [Pocket](https://getpocket.com/).

**Comment by exekutive** [comment]
I get it. I still don't like it. Unfortunately it's deal-breaker for me.

**Comment by jancborchardt** [comment]
Could you describe:
- What you like about the previous view?
- How the current view does not fulfil that?

**Comment by exekutive** [comment]
I just do. Is it really important _why_?

I guess I find it more efficient. I wonder ... when you're browsing large numbers of files in your operating system, do use icon view?

**Comment by jancborchardt** [comment]
> I just do. Is it really important why?

Since you are requesting something – yes, you should explain, so we can understand, and design a proper solution. If we don’t have clear requirements, then the software will just be based on assumptions.

> when you're browsing large numbers of files in your operating system, do use icon view?

Well yes – I always use icon view because file previews are much more telling about something than names.

**Comment by exekutive** [comment]
I think I made my requirements were pretty clear. List: yes, Icons: no. Pretty hard to misinterpret I think. Obviously you think you know what is best for everybody else.

>Well yes – I always use icon view

Really? I think you are playing stupid, but OK I will spell it out for you.  Even if your OS showed previews for every single file, what if you're more interested in details like the file size, or date etc., and you need to quickly compare large numbers of them? You are going to study the icons and find out?  In the case of bookmarks I am most interested in titles, URLs and dates, and they are much easier to read and scan through in column form.

What does the preview show anyway? A whole webpage squished into a few hundred pixels? Right .... super useful.

**Comment by jancborchardt** [comment]
@exekutive **Keep in mind that we have both [design guidelines](https://nextcloud.com/design/) as well as a [Code of Conduct](https://nextcloud.com/code-of-conduct/). If you disagree with the way we do things and don’t express that in a considerate or respectful manner, this community is not for you.**

This way of talking is just incredibly uncomfortable. Understand that if you request things from people – especially when they do it in their free time and provide it to you for free (!) – you should be nice and not say stuff like "Obviously you think you know what is best for everybody else."

That said, thanks for spelling it out – that is literally what I mean by "requirements" – I can not read your mind. That it takes multiple times asking and being barked at in reply is just not cool, and won’t lead to quicker results.

The preview would show for example the main image of a blog post, or the preview of a video, or the "above the fold" of a website – very simple. Compare it to Pocket:
![](https://www.exordo.com/blog/wp-content/uploads/2018/02/Screen-Shot-2018-02-15-at-14.29.59.png)

**Comment by exekutive** [comment]
(Sorry I was a little frustrated because it seems obvious to me.  I do appreciate your work which is why I'm here giving my time to help make it better. I cleaned up my comments.)

The icon view is useful and has its place. The same goes goes for list view.

**Comment by lexelby** [comment]
I'm sorry to say that I also really wish I could have the list view back as an option.  For my workflow, version 0.12 is a major downgrade for me.  I'll try to explain why.

I use Nextcloud Bookmarks to curate content for my newsletter, [SRE Weekly](https://sreweekly.com).  I edit the descriptions and set tags, and then I run a script that pulls this information from the bookmarks API and produces an issue of my newsletter.

For me, the most important part of Nextcloud Bookmarks is the _descriptions_, not the bookmarks themselves.  As far as I can tell, the pocket-style view in the new version doesn't even show me that I've entered a description for a bookmark, much less the actual content I've edited.

As exekutive put it, for me this is unfortunately a deal-breaker.  I can't upgrade; it'll totally kill my workflow.

That said, I only found this out because I _tried_ upgrading, hoping the new version would help with some workflow issues I already have.  In the list view, when I edit a description or tags and hit 'save', it bumps me back up to the top of the list, which can be pretty disruptive.  I was hoping for some kind of ajaxy update interface.

Please let me know if I can better help you understand my use case.  For now, I've downgraded to v11 (thankfully downgrading seems to work) but I could try out a new pre-release version if you have something you'd like me to look at.

BTW, I should mention that nextcloud bookmarks itself allowed me to get off of pinboard.in!  I was using pinboard to curate content for my newsletter previously, but they just went down too often.  I love that all the work on nextcloud bookmarks has made it into a viable replacement that let me cancel my pinboard subscription.

**Comment by marcelklehr** [comment]
> For me, the most important part of Nextcloud Bookmarks is the descriptions, not the bookmarks themselves. As far as I can tell, the pocket-style view in the new version doesn't even show me that I've entered a description for a bookmark, much less the actual content I've edited.

@lexelby If you open the details of a bookmark, you can see the description. We may have to simplify the accessibility of this, but it does work.

**Comment by marcelklehr** [comment]
> In the case of bookmarks I am most interested in titles, URLs and dates, and they are much easier to read and scan through in column form.

In my opinion, the majority of people will probably not remember the date, the URL and perhaps not even the title of the web page they are looking for in their bookmarks. Thus visuals like the preview images and the favicons that show the content of the page are big improvements for the user experience of this group of people.

Since, as @jancborchardt noted, resources for the work on this app are limited, I'll opt to focus on one view, only.

**Comment by jancborchardt** [comment]
And maybe a part-solution for @lexelby’s case is to have a navigation entry on the left for "With description" much like "Untagged" https://github.com/nextcloud/bookmarks/pull/518 – that way you could directly see which are important.
