### ISSUE TITLE
UI: Improve cards appearence

### ISSUE THREAD

**Issue by TtuxX** [nextcloud/bookmarks#536]
_(referring to issue #535 )_

@marcelklehr Few appearence improvements I have started to make on my own instance today and that need to be further polished :)

At the moment, the main remaining issues I see with the new CSS modifications hereafter are the following ones (apart from CSS changes being dirty):
- `panel` div height is not unified as its height changes if bookmark has only one or more lines,
- `popovermenu` displays behind other cards.

***

**Before**:

![image](https://user-images.githubusercontent.com/6570830/43216342-139843ac-903f-11e8-91b5-641fcfc34cb0.png)

**After**:

![image](https://user-images.githubusercontent.com/6570830/43216836-4bf1d5b4-9040-11e8-9d50-c5e02cdfd85e.png)

***

**CSS changes**:

.bookmark-card {
    background-position: top !important;
    box-shadow: 0 1px 4px rgba(77, 77, 77, 0.6),inset 0 0 15px rgba(0, 0, 0, 0.1);
    border-radius: 10px 10px 10px 10px;
}

.bookmark-card .panel {
    padding: 10px 6px 6px 10px;
    background: rgba(0, 0, 0, 0.7);
    border-radius: 0px 0px 10px 10px;
}

.bookmark-card .toggle-actions {
    top: 36%;
    right: 3px;
}

.bookmark-card h2 {
    font-size: 18px;
}

.bookmark-card:hover {
    box-shadow: 0 1px 10px rgba(77, 77, 77, 0.75);
    transform: scale(1.03);
    transition: transform .3s;
}

***

**Further improving cards**:

I started thinking about this:

![image](https://user-images.githubusercontent.com/6570830/43217546-3a533dbe-9042-11e8-8e6d-17f13e25a57a.png)

***
Discussion is completely open as always, please do not hesitate @marcelklehr to share your thoughts/suggestions on any of these ideas ! :)

**Comment by marcelklehr** [comment]
Thank you for your input! I like that you removed that shadow under the title in the cards for a more opaque background as it increases readability, looks cleaner and even improves UX as clicking on the panel has a different effect than the background. I also like your adjustment of the paddings. I understand that the inset shadows make the previews very dark on small screens. When losing them completely, however, the previews feel to immediate to me. Thus I leaft them in, but decreased them by a third. The rounded corners look nice, but don't fit very well with the rest of the nextcloud design, IMHO, so I didn't overtake those and in fact made the sharp edges and corners more intentional by losing the drop shadow on hover and instead increasing the opacity.
Aligning the backgrounds to the top is something that was in the back of my mind as well. :+1:
Your changes inspired me to question some other choices. The favicons felt a bit neglected to me: too small, too hard to make out, especially on the dark background as they're often chosen for a bright background in the browser UI. To remedy this, I changed the panel background to white and doubled the size of the favicons, while also making them clickable along with the link.

> panel div height is not unified as its height changes if bookmark has only one or more lines,

I fixed this as well.

> popovermenu displays behind other cards.

I cannot replicate this. Was that because of your modifications?

I played a little with a sliding animation revealing the full title in the cards, but decided not to do it. Mainly because it moves the pointer target mid-way when aiming for the actions button (which could be moved to the top admittedly, but that wouldn't be very intuitive, I think). So, for now, when the user wants to see the full title, they need to click the preview to see the details.

I look forward to your feedback on my changes :)

**Comment by TtuxX** [comment]
Thank you for your detailed thoughts ! :)

Hmm I don't have much to say, it was just random thoughts on appearence ; you integrate what you like and don't integrate what you don't  :)

>I understand that the inset shadows make the previews very dark on small screens. When losing them completely, however, the previews feel to immediate to me.

Yes, I can understand :/

>Thus I left them in, but decreased them by a third.

Ok!

>The rounded corners look nice, but don't fit very well with the rest of the nextcloud design, IMHO, so I didn't overtake those and in fact made the sharp edges and corners more intentional by losing the drop shadow on hover and instead increasing the opacity.

Yes it is true that it is not completely coherent and differs quite a bit from the more squared-design nextcloud UI in general.

>The favicons felt a bit neglected to me: too small, too hard to make out, especially on the dark background as they're often chosen for a bright background in the browser UI. 

Yeah, I thought the same !

>To remedy this, I changed the panel background to white [...]

To make the bookmark title more visible do you think it could be relevant to make its text a little bit more bold and to remove its underline ?

>[...]and doubled the size of the favicons, while also making them clickable along with the link.
Great ! :+1: 

>I cannot replicate this. Was that because of your modifications?

Yes, so no worries :)

>So, for now, when the user wants to see the full title, they need to click the preview to see the details.

Ok!

***
Apart from this, what is your opinion about the idea of slight CSS animation change, with a slight zoom of the card on hover to reinforce the selection and hover shadow variation ?

.bookmark-card:hover {
transform: scale(1.03);
transition: transform .3s;
}

**Comment by TtuxX** [comment]
>there's no middle ground that completely satisfied me, the next step in boldness was too bold for my taste as it looked pretty clunky. 

Agree, I have experimented the same while testing..

>it didn't fit too well in the flat design, imho.

Ok :)

>Just pushed the new changes.

Great, thank you very much ! When panel is opened and that you click on another bookmark, it re-triggers the opening animation. Maybe if panel has already been opened, just display the new bookmark content without animation ?

**Comment by marcelklehr** [comment]
[v0.12.0-rc4](https://github.com/nextcloud/bookmarks/releases/tag/v0.12.0-rc4) released
