### ISSUE TITLE
Feature Request: Customizable Thumbnails

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#554]
Hi there,

First of all, a quick note to voice my appreciation for the project- Bookmarks is a very handy tool that I use extensively, and it just keeps getting better. Thank you for your hard work :)

I have noticed that occasionally a link won't pull a thumbnail image, or the thumbnail image choice is less than ideal (user's avatar when bookmarking a github repo, for instance).

It would be awesome if we could customize the thumbnail, either with an uploaded file in Nextcloud Files or even just an image URL or something.

It's not an emergency, but if you ever get the time, I think it would be a cool addition to Bookmarks. :)

Thanks!

**Comment by marcelklehr** [comment]
Hey,

Sorry for the delay. I've thought about this every once in a while and it will probably not happen. I think, instead of letting users spend time to figure out how to customize their bookmarks' previews, the previews should be so good by default, that no one feels the need to change them.

Let me elaborate on how previews are generated. The default preview method is not very smart, admittedly. It just scrapes the bookmark URL and checks for meta tags like opengraph, or twitter card. If it doesn't find those, it'll scan the page and take the largest image in there. Additionally it's possible to setup integration of a [screeenly server](https://github.com/stefanzweifel/screeenly) in the admin settings that will generate actual screenshots. Currently, the app will always choose the default previews if they are available and will only use the screeenly server as a fallback. My original rationale for this was that I thought opengraph images for things like youtube videos and news articles would be better suited than a simple screenshot as they are ideally handpicked by the author of the work.

Feedback on how to improve the preview logic is greatly appreciated, though.

**Comment by tossican** [comment]
I would also like to throw in my vote for user selectable thumbs... 

I understand your sentiment about auto-generating thumbs. It would be awesome! However, it is not the case now.. And I don't imagine it will be an easy fix.. 

I currently have many sites where:
* The selected image gives no indication what the content actually is.
* Present as just a generic login screen. (Using screenly)
* Show as a (seemingly random) solid colored box (without screenly).
* Displays "Content not available in your region" or other such messages (with Screenly).
* Show as a generic box of illegible text.
* Displays the site's screenshot in a different language then mine. (With Screenly)

Additionally, I could imagine a number of reasons one might want to obscure the contents of a website, while still allowing the thumb to represent something to them.

A user selectable override (per bookmark), would be a relatively simple fix for both reasons.

**Comment by marcelklehr** [comment]
While I agree that the previews are not always ideal, I seriously doubt that requiring the user to create and upload images for all their websites by hand is a viable alternative.
