### ISSUE TITLE
FR: REST Endpoint to get thumbnail for Bookmark

### ISSUE THREAD

**Issue by zachtib** [nextcloud/bookmarks#663]
I'm working on an Android client for Nextcloud Bookmarks and would like to be able to sync down the thumbnails used in the web interface for Bookmarks in order to display those thumbnails in the app.

While there's a pretty straightforward URL, like https://server.url/apps/bookmarks/bookmark/90/image, it relies on authentication from the browser sessions rather than the basic HTTP Auth the rest of the site uses, so it's a little harder to grab from an Android app just by using the API.

Ideally, I'd like the url added to the Bookmark model as an additional field, like `thumbnailUrl` for the Bookmarks that have a Thumnail (some of them don't seem to on my setup) so that I know which ones to download.

**Comment by marcelklehr** [comment]
Hey :)
Sorry for the delay! I'm glad work on android is being picked up again :)
Exposing a field on the model is tricky, because the previews are reevaluated regularly, so that field would be subject to change. But exposing the image endpoint as part of the API is pretty straightforward, I'll definitely get to that. Thanks for the feedback!

**Comment by marcelklehr** [comment]
v0.17.0 has this now :)
