### ISSUE TITLE
Feature request: retain bookmark order

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/bookmarks#778]
Would be nice to have the bookmarks retain the order when syncing with Floccus.
I have my bookmarks somewhat sorted by relative order of the bookmarks. When reviewing the bookmarks on the server I do not see a way to view them without being resorted (desorted).

**Comment by weeman1337** [comment]
Does anybody know whether Floccus sends the order to Nextcloud?

**Comment by marcelklehr** [comment]
Yes, the order is stored in nextcloud bookmarks, it's just not displayed or possible to change in the web UI.

**Comment by weeman1337** [comment]
Thanks @marcelklehr . I assume it is the `index` column of the `bookmarks_tree` table, right?

If I click on a folder in the front-end I am not able to find the request and response of the item list. Could you give me a hint?

![image](https://user-images.githubusercontent.com/6216686/85121651-708c5300-b225-11ea-829b-0459c97ed38b.png)

**Comment by marcelklehr** [comment]
Currently the UI uses two older endpoints, namely `bookmark` and `folder`. There is also a childorder endpoint that gives you only the order and the ids without any content fields, and finally, there's the children endpoint that gives you the contents in order. All documented over here: https://nextcloud-bookmarks.readthedocs.io/en/latest/

I've neglected implementing this so far because I felt, if the order was displayed in the UI, it should also be possible to modify it, but implementing *that* is probably quite a hassle. I'm also happy with just a PR for only displaying in order, should you want to work on this :)

**Comment by weeman1337** [comment]
> I'm also happy with just a PR for only displaying in order, should you want to work on this :)

Agree. Lets start with this. The current use-case on my side is sync bookmarks between browsers. Bonus: Online access via Nextcloud. But at the moment it is annoying using the web app because I do not find the bookmarks in my bookmark jungle :D

Any opinions about how to name the order option?
* _Original order_
* _Source order_

**Comment by marcelklehr** [comment]
Maybe *custom order*? :man_shrugging:

**Comment by InfamousUser** [comment]
I'm also trying to have bookmark sync between browsers, but if they don't sort the same way and it's not possible to change order it's not of use. We need Chrome-like bookmark sync! But I don't want to send my bookmarks to Google.

**Comment by marcelklehr** [comment]
To be clear: The bookmarks app does store the bookmarks order for syncing. It's just not displayed in the UI, yet.

**Comment by InfamousUser** [comment]
Uhm would you kindly tell me how to enable this original display order, because it is still displayed alphabetically for me?
Using v3.3.3.

**Comment by InfamousUser** [comment]
I tried out the new sorting settings but none of the 4 settings available display the bookmarks in order, all of them resort the bookmarks.
To clarify; I have done a fresh sync and all folders are in the same order for all 4 options, bookmarks inside the folders get reordered depending on the options, but none of the options retains the bookmark orders - all of them are different order than in my browser from which I synced them.

**Comment by marcelklehr** [comment]
@InfamousUser the new sort order feature has not yet been released.

**Comment by InfamousUser** [comment]
Oh my bad, sorry, don't know how GitHub works.

**Comment by InfamousUser** [comment]
I just updated to the new version with the original sort order available. Just wanted to say thank you very much for adding this, this makes it perfectly usable for me now! Very helpful!

**Comment by sausix** [comment]
I did an initial sync of my bookmarks into Nextcloud (merge option) and the original order of the bookmarks has changed.

Folders have mooved before single bookmarks. I want some bookmarks on top level to appear before folders.
So this order should also be preserved.

**Comment by InfamousUser** [comment]
I've just opened up bookmarks on Nextcloud and it opened two different sorts when I reselected "custom order". Further, it does not appear that the order is retained after making changes in browser, they stay in the starting position.

**Comment by sausix** [comment]
@InfamousUser No, I did some restarts and manual syncs.

But after I had manually resorted my bookmarks, they kept the order.
Until the Nextcloud app does not show the correct order and does not allow dragging for resorting, it's a lot of guessing what actually happens.

**Comment by marcelklehr** [comment]
This is likely a floccus issue, as floccus does not propagate the order information on the initial sync.
