### ISSUE TITLE
Feature Request: How to make sure to not run into incompabilities after codechange

### ISSUE THREAD

**Issue by JimmyKater** [nextcloud/bookmarks#786]
**Is your feature request related to a problem? Please describe.**
seemingly the code of bookmarks was updated and thus it needs to have some more php-extentions installed. as @marcelklehr already told me (when i was filing an issue under floccus, because I thought it would be a problem with it --> https://github.com/marcelklehr/floccus/issues/359) the app can't install any php-extension itself.
if you let bookmarks autoupdate you sure enough would run into problems. i think that's unwanted. 

**Describe the solution you'd like**
i think it would be great if - in that or future cases - some instance would first install the missing dependencies/extensions and then let bookmarks autoupdate again. 
since i am no dev (shame on me) - i dunno if the following suggestion would make sense.
if you discover the need of installing new dependencies talk to nc-server devs and tell them what you need. and why. - after they have put the changes into the code they would tell you from which nc-version on the new stuff would work. 
so that you would know from when on autoupdate would be "allowed".

would such a thing work? or am i thinking too simple?

anyways: keep the good work up! thanks for everything <3

**Comment by marcelklehr** [comment]
Thank you for your thoughtful feedback.

I believe the issue you talk about occurred because I ignored or failed to apply the specifics of semantic versioning, which dictates that breaking changes be indicated by a major version number bump -- which I didn't do, for whatever reason. I am reasonably certain that nextcloud is not (and should not) be able to install php extensions (which are usually OS packages) on your system.

However, I agree that the current situation is not ideal. I have thus just released v1.1.2 which reverts breaking changes introduced in v1.0.8 and restores compatibility with php v7.0 and at the same time have released v2.0.1 which reintroduces this breaking change while adhering to semantic versioning as well as dropping support for nextcloud <=15 and documenting the additional requirements in the app store description.

So, if I have successfully avoided any more screw-ups, you should be able to resolve any issues by updating to v1.1.2 on nextcloud <=15, and updating to v2.0.1 on nextcloud 16 (and of course ensuring that you install the relevant extensions manually).
