### ISSUE TITLE
if import files are too big bookmarks should break import file into manageable chunks

### ISSUE THREAD

**Issue by snassar** [nextcloud/bookmarks#81]
It appears that import files over a certain size are too much for one import. Bookmarks should be able to break down the import file into manageable chunks. Alternatively it should let the user know what the limits are.

**Comment by Chouchen** [comment]
This app can't control the file size before the upload so it can't split the file. The user should do it.
Since upload limits is bound to PHP configuration, the user should configure it himself (or ask for his admin to do it)

The only thing we can do IMHO is indicate somewhere (but where?) the PHP current upload limit.

**Comment by snassar** [comment]
My PHP upload limits are larger than the file I am uploading.

**Comment by Chouchen** [comment]
Did you check `upload_max_filesize` **and** `post_max_size` ?
