### ISSUE TITLE
App Save to Nextcloud Bookmarks - blank screen

### ISSUE THREAD

**Issue by toniozzz** [nextcloud/bookmarks#867]
**Describe the bug**
I think this is not a bug.
When i try to save a bookmark with Save to Nextcloud Bookmarks, i have a blank screen.

**To Reproduce**
1. On my Android Phone, open Chrome
2. On Chrome, share the bookmark 
3. In the liste of app, select save to bookmarks
4. Connect to Nextcloud
5. Blanj screen, the bookmark is not recorded

**Expected behavior**
Record the bookmark

**Desktop (please complete the following information):**
 - OS: Android 9
 - Chrome mobile
 - v78

**Server (please complete the following information):**
 - OS: Archlinux ARM
 - HTTP server: nginx
 - Database mariadb
 - PHP version: PHP 7.3
 - Nextcloud version: 17.0.0

**Comment by marcelklehr** [comment]
Hello @toniozzz 
I'm sorry for your troubles. As far as I understand your issue is about the *Save to Nextcloud bookmarks* android app. However, this is the repository of the server-side nextcloud bookmarks app. Thus there's nothing I can do about your issue here. I recommend to try and contact the app's author about the issue.
