### ISSUE TITLE
[Feature request] I want to edit Bookmar-Links

### ISSUE THREAD

**Issue by GambaJo** [nextcloud/bookmarks#875]
Sometimes the links in the bookmarks are like "https://www.whatever.org/wbb2/forum.php".
I would like to edit them, so I can do something like this "https://www.whatever.org".

I think for a bookmark app this should be a standard feature.

**Comment by j-ed** [comment]
So the easiest way to prevent editing of an url is by correcting the url right before you press the "create" arrow 😉

**Comment by GambaJo** [comment]
Nobody is perfect, mistakes happen.
And a URL can change.

**Comment by GambaJo** [comment]
I'm confused. When I look at the screenshot on [the descripton page](https://apps.nextcloud.com/apps/bookmarks), there is a edit function.

![Bookmarks](https://user-images.githubusercontent.com/1378907/71180008-9a15f300-2271-11ea-9adc-71aebc0a612e.png)

**Comment by marcelklehr** [comment]
Hello @GambaJo 
thank you for your feedback. I'm always happy to hear user's ideas and input on the app :)
It used to be possible indeed to edit the URL of a bookmark. However, with the recent rewrite of the UI, I removed this functionality as I didn't see its particular usefulness: As @j-ed noted, it's possible to remove bookmarks and create new ones, which to me seemed more in line with the idea that the URL is the primary identifier of a bookmark, which shouldn't change. I do recognize now, that there may be legitimate use cases for editing a bookmark's URL, if only because it's more convenient than recreating a bookmark with a slightly different URL.

**Comment by psipherious** [comment]
Funny I just went searching for exactly this and see the conversation is very recent on it. I only just installed Nextcloud for the first time a couple days ago and have been getting it all setup and added the Bookmarks app to find exactly the problem you mention of not being able to edit links and I fully agree it's a little nuts.

I edit links all the time. I have a decent amount bookmarks (probably close to 1000) and I often go through them and re-sort organize older ones - many times I find some of my older ones are links to non-SSL versions of a site so I want to edit them JUST to add https to the beginning and yes, it's **far more convenient** to simply edit them than to delete it and remake it and refile it.

So you can count me as another vote towards wanting the ability to edit URL's once again (as it seems this used to be a feature).
