### ISSUE TITLE
Add REST API endpoint for getting folders and bookmarks

### ISSUE THREAD

**Issue by dave-kennedy** [nextcloud/bookmarks#907]
I'd like to display a list of subfolders and bookmarks in a folder, similar to how the web UI displays them. But I don't see a single REST API endpoint for this purpose. Instead, it seems that I have to get the bookmarks in a folder, then I have to get the subfolders.

**Comment by marcelklehr** [comment]
Yes, this is how the REST API works.

**Comment by dave-kennedy** [comment]
@marcelklehr did you add a new endpoint to the API before you closed this? I don't see it...

To clarify, I'm looking for a single endpoint that returns both folders and bookmarks.

**Comment by marcelklehr** [comment]
@dave-kennedy I did not add it before closing this, but I have since realized that this would be a clear-cut way to improve performance with floccus. So, in the end, I did implement this :smile: Here are the docs: https://github.com/nextcloud/bookmarks/blob/master/docs/folder.rst#get-folder-s-contents
