### ISSUE TITLE
Incorrect string value: '\xF0\x9F\x8C\xA9 N...' for column `db_table`.`oc_bookmarks`.`title`

### ISSUE THREAD

**Issue by oparoz** [nextcloud/bookmarks#908]
**Describe the bug**

Sync stops working because of a bookmark

**To Reproduce**
1. Bookmark "https://github.com//rookie0//nextcloud-sharing-path" ?

**Expected behavior**

Sync should work (ideally skipping bad ones with a warning)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Brave
 - Version: 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

**Server (please complete the following information):**
 - OS: FreeBSD 12.1
 - HTTP server:  Apache 2.4 + PHP-FPM
 - Database: MariaDB 10.2
 - PHP version: PHP 7.3
 - Nextcloud version: 17.0.2
 - Bookmarks app version: 2.3.4

**Additional context**

Look at the title of the bookmark, it has a UTF-8 character.
My DB doesn't have 4-byte support.

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_bookmarks` (`url`, `title`, `user_id`, `public`, `added`, `lastmodified`, `description`) VALUES(?, ?, ?, ?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), ?)' with params ["https:\/\/github.com\/rookie0\/nextcloud-sharing-path", "GitHub - rookie0\/nextcloud-sharing-path: \ud83c\udf29 Nextcloud app to enhance files sharing usage as CDN origin storage", "bookmarks", 0, ""]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x8C\xA9 N...' for column `db_table`.`oc_bookmarks`.`title` at row 1
```

**Comment by marcelklehr** [comment]
Hey there,
I'm sorry you ran into trouble.
The problem is: There is no way to tell why the server is having trouble on the client-side and on the server-side I don't think there is a way to know the charset of the database. Is there anything in particular stopping you from converting your db to utf8mb4? This would solve this problem once and for all. Alternatively, you can alter the titles of your bookmarks to omit the emojis. :man_shrugging:
